
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nemoz
 */
public class FoodOrder extends javax.swing.JFrame {

    ArrayList<String> orderedKeys = new ArrayList();
    TempOrder tempOrders = new TempOrder();
    String menuKey;
    int categoryID;
    int menuID;
    int menuType;
    int amount;
    double total;
    double discounted;
    
    DefaultComboBoxModel<String> menuNameModel = new DefaultComboBoxModel();
    DefaultComboBoxModel<String> menuTypeModel = new DefaultComboBoxModel();
    
    public FoodOrder(javax.swing.JFrame parent) {
        initComponents();
        
        menuSelector.setModel(menuNameModel);
        menuPriceSelector.setModel(menuTypeModel);
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                setVisible(false);
                parent.setVisible(true);
            }
        });
        
        setVisible(true);
        clear();
    }
    public void clear() {
        categoryID = 0;
        setAmount(1);
        categorySelectorActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        proceedButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        amountField = new javax.swing.JTextField();
        amountDec = new javax.swing.JButton();
        amountInc = new javax.swing.JButton();
        menuPreview = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        categorySelector = new javax.swing.JButton();
        menuSelector = new javax.swing.JComboBox<>();
        menuPriceSelector = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        totalField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel1.setText("จำนวน");

        cancelButton.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        cancelButton.setText("ยกเลิก");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        proceedButton.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        proceedButton.setText("เริ่มสั่งอาหาร");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        orderButton.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        orderButton.setText("เพิ่มอาหาร");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        amountField.setEditable(false);
        amountField.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N

        amountDec.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        amountDec.setText("+");
        amountDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountDecActionPerformed(evt);
            }
        });

        amountInc.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        amountInc.setText("-");
        amountInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountIncActionPerformed(evt);
            }
        });

        menuPreview.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N

        categorySelector.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        categorySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorySelectorActionPerformed(evt);
            }
        });

        menuSelector.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        menuSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSelectorActionPerformed(evt);
            }
        });

        menuPriceSelector.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        menuPriceSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPriceSelectorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel2.setText("รวมราคา");

        totalField.setEditable(false);
        totalField.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel3.setText("ลดราคา");

        totalField1.setEditable(false);
        totalField1.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proceedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addComponent(menuPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuPriceSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amountInc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amountDec)
                                .addGap(13, 13, 13)
                                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categorySelector, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(menuSelector)
                    .addComponent(menuPriceSelector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amountInc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amountDec, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void categorySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorySelectorActionPerformed
        categoryID = Math.floorMod(categoryID, Database.categories.size()) + 1;
        
        menuNameModel.removeAllElements();
        for (Menu menu : Database.menus) {
            if (menu.category.id == categoryID)
                menuNameModel.addElement(menu.name);
        }
        
        menuSelector.setSelectedIndex(0);
        
        switch (categoryID) {
            case 1 -> { categorySelector.setIcon(Utility.getImageLocal(getClass(), "/data/MainDish.png", categorySelector.getWidth() - 15, categorySelector.getHeight() - 15));  }
            case 2 -> { categorySelector.setIcon(Utility.getImageLocal(getClass(), "/data/SubDish.png", categorySelector.getWidth() - 15, categorySelector.getHeight() - 15)); }
            case 3 -> { categorySelector.setIcon(Utility.getImageLocal(getClass(), "/data/Salad.png", categorySelector.getWidth() - 15, categorySelector.getHeight() - 15)); }
            case 4 -> { categorySelector.setIcon(Utility.getImageLocal(getClass(), "/data/Drink.png", categorySelector.getWidth() - 15, categorySelector.getHeight() - 15)); }
        }
    }//GEN-LAST:event_categorySelectorActionPerformed

    private void menuSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSelectorActionPerformed
        menuID = Math.max(menuSelector.getSelectedIndex(), 0) + 1;
        menuKey = Menu.getUID(categoryID, menuID);

        menuType = 0;
        menuTypeModel.removeAllElements();
        for (double price : Database.menuMap.get(menuKey).price) {
            menuTypeModel.addElement("฿ %.2f".formatted(price));
        }
        
        menuPriceSelector.setSelectedIndex(0);
        setAmount(1);
        
        orderButton.setEnabled(!orderedKeys.contains(menuKey));
        amountInc.setEnabled(!orderedKeys.contains(menuKey));
        amountDec.setEnabled(!orderedKeys.contains(menuKey));
        if (orderedKeys.contains(menuKey))
            amountField.setText("" + tempOrders.amounts.get(orderedKeys.indexOf(menuKey)));
        
        menuPreview.setIcon(Utility.getImageFromURL(Database.menuMap.get(menuKey).pictureURL, menuPreview.getWidth(), menuPreview.getHeight()));
    }//GEN-LAST:event_menuSelectorActionPerformed

    private void menuPriceSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPriceSelectorActionPerformed
        menuType = Math.max(menuPriceSelector.getSelectedIndex(), 0);
        setAmount(amount);
    }//GEN-LAST:event_menuPriceSelectorActionPerformed

    private void amountIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountIncActionPerformed
        setAmount(amount - 1);
    }//GEN-LAST:event_amountIncActionPerformed

    private void amountDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountDecActionPerformed
        setAmount(amount + 1);
    }//GEN-LAST:event_amountDecActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        Menu menu = Database.menuMap.get(menuKey);

        setAmount(amount);
        
        tempOrders.menus.add(menu);
        tempOrders.totals.add(total);
        tempOrders.discounted.add(discounted);
        tempOrders.types.add(menuType);
        tempOrders.amounts.add(amount);
        
        orderedKeys.add(menuKey);
        orderButton.setEnabled(false);
        amountInc.setEnabled(false);
        amountDec.setEnabled(false);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
        Main.instance.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        if (tempOrders.menus.isEmpty()) { return; }
        setVisible(false);
        new FoodOrderList(this, tempOrders);
    }//GEN-LAST:event_proceedButtonActionPerformed

    void setAmount(int amount) {
        this.amount = Math.max(amount, 1);
        amountField.setText("" + this.amount);
        
        double rawPrice = Database.menuMap.containsKey(menuKey) ? (Database.menuMap.get(menuKey).price[menuType] * this.amount) : 0;
        discounted = ((categoryID == 1 && Database.instance.order.member != null) ? rawPrice * 0.05 : 0);
        total = ((categoryID == 1 && Database.instance.order.member != null) ? rawPrice * 0.95 : rawPrice);
        
        totalField.setText("฿ %.2f".formatted(total));
        totalField1.setText("฿ %.2f".formatted(discounted));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodOrder(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amountDec;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton amountInc;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton categorySelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel menuPreview;
    private javax.swing.JComboBox<String> menuPriceSelector;
    private javax.swing.JComboBox<String> menuSelector;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton proceedButton;
    private javax.swing.JTextField totalField;
    private javax.swing.JTextField totalField1;
    // End of variables declaration//GEN-END:variables
}
