/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nemoz
 */
public class FoodOrderList extends javax.swing.JFrame {

    FoodOrder frame;
    TempOrder data;
    int page = 0;
    
    public FoodOrderList(FoodOrder orderFrame, TempOrder data) {
        initComponents();
        
        this.frame = orderFrame;
        this.data = data;
        
        /*
        System.out.println(java.util.Arrays.toString(data.menus.toArray()));
        System.out.println(java.util.Arrays.toString(data.types.toArray()));
        System.out.println(java.util.Arrays.toString(data.amounts.toArray()));
        System.out.println(java.util.Arrays.toString(data.discounted.toArray()));
        System.out.println(java.util.Arrays.toString(data.totals.toArray()));
        */
        
        setPage(0);
        updatePrice();
        
        setVisible(true);
    }

    void setPage(int p) {
        try {
            if (!data.menus.isEmpty()) {
                page = Math.clamp(p, 0, data.menus.size() - 1);

                Menu menu = data.menus.get(page);

                pageLabel.setText("%d / %d".formatted(page + 1, data.menus.size()));
                pageDetail.setText("%s (%s) | ฿ %.2f × %d ชิ้น | ส่วนลด : %.2f | ราคา : ฿ %.2f".formatted(
                        menu.name, menu.category.name,
                        menu.price[data.types.get(page)], 
                        data.amounts.get(page), 
                        data.discounted.get(page), 
                        data.totals.get(page)));

                menuPreview.setIcon(Utility.getImageFromURL(menu.pictureURL, menuPreview.getWidth(), menuPreview.getHeight()));
            } else { frame.clear(); frame.setVisible(true); dispose(); }
        } catch (Exception e) { e.printStackTrace(); dispose(); }
    }
    void updatePrice() {
        double total = 0.0f; for (double subTotal : data.totals) { total += subTotal; }
        double discounted = 0.0f; for (double subTotal : data.discounted) { total += subTotal; }
        
        totalField.setText("฿ %.2f".formatted(total));
        discountedField.setText("฿ %.2f".formatted(discounted)); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prevPage = new javax.swing.JButton();
        nextPage = new javax.swing.JButton();
        totalField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        menuPreview = new javax.swing.JLabel();
        discountedField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pageLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        deleteMenu = new javax.swing.JButton();
        pageDetail = new javax.swing.JLabel();
        orderStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        prevPage.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        prevPage.setText("<");
        prevPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevPageActionPerformed(evt);
            }
        });

        nextPage.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        nextPage.setText(">");
        nextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageActionPerformed(evt);
            }
        });

        totalField.setEditable(false);
        totalField.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel2.setText("รวมราคา");

        menuPreview.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N

        discountedField.setEditable(false);
        discountedField.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel3.setText("ลดราคา");

        pageLabel.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        pageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageLabel.setText("1 / 1");

        returnButton.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        returnButton.setText("กลับ");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        deleteMenu.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        deleteMenu.setText("ลบรายการ");
        deleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuActionPerformed(evt);
            }
        });

        pageDetail.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        pageDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        orderStart.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        orderStart.setText("สั่งอาหาร");
        orderStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pageDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPreview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(discountedField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(prevPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextPage))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orderStart, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevPage)
                    .addComponent(nextPage)
                    .addComponent(pageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderStart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prevPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevPageActionPerformed
        setPage(page - 1);
    }//GEN-LAST:event_prevPageActionPerformed

    private void nextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageActionPerformed
        setPage(page + 1);
    }//GEN-LAST:event_nextPageActionPerformed

    private void deleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuActionPerformed
        frame.orderedKeys.remove(page);
        data.menus.remove(page);
        data.amounts.remove(page);
        data.discounted.remove(page);
        data.totals.remove(page);
        data.types.remove(page);
        
        setPage(page - 1);
        updatePrice();
    }//GEN-LAST:event_deleteMenuActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        frame.clear();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void orderStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderStartActionPerformed
        Database.instance.process(data);
        Main.instance.setVisible(true);
        setVisible(false);
        frame.dispose();
        dispose();
    }//GEN-LAST:event_orderStartActionPerformed
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodOrderList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodOrderList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodOrderList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodOrderList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodOrderList(null).setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteMenu;
    private javax.swing.JTextField discountedField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel menuPreview;
    private javax.swing.JButton nextPage;
    private javax.swing.JButton orderStart;
    private javax.swing.JLabel pageDetail;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JButton prevPage;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
