
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nemoz
 */
public class Login extends javax.swing.JFrame {

     javax.swing.JFrame main;
    
    public Login() {
        initComponents();
        QRLabel.setIcon(Utility.getImageLocal(getClass(), "/data/SampleQR.png", QRLabel.getWidth(), QRLabel.getHeight()));
    }
    public Login(javax.swing.JFrame main) {
        this();
        
        this.main = main;
        setVisible(true);
        requestFocus();
    }

    @Override
    public void dispose() {
        if (main != null) {
            main.setVisible(true);
            main.requestFocus();
        }
        super.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QRLabel = new javax.swing.JLabel();
        GuestButton = new javax.swing.JButton();
        PhoneButton = new javax.swing.JButton();
        GuestButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        QRLabel.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N

        GuestButton.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        GuestButton.setText("ลูกค้าทั่วไป");
        GuestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestButtonActionPerformed(evt);
            }
        });

        PhoneButton.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        PhoneButton.setText("เข้าสู่ระบบด้วยเบอร์โทร");
        PhoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneButtonActionPerformed(evt);
            }
        });

        GuestButton1.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        GuestButton1.setText("เรียกดูบิล");
        GuestButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuestButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(QRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(PhoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(GuestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(GuestButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneButtonActionPerformed
        String phone = JOptionPane.showInputDialog("Input your Phone Number:");
        
        if (phone != null && !phone.isEmpty()) {
            Database.instance.login(phone);
            
            Member member = Database.instance.order.member;
            if (Database.instance.order == null && member == null) {
                JOptionPane.showMessageDialog(this, "Invalid", "Failed", JOptionPane.ERROR_MESSAGE);
            } else {
                String message = "Welcome : %s (%s)".formatted(member.name, member.phone);
                JOptionPane.showMessageDialog(this, message, "Sucess", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            
        }
    }//GEN-LAST:event_PhoneButtonActionPerformed

    private void GuestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestButtonActionPerformed
        if (Database.instance.order == null) Database.instance.begin();
        dispose();
    }//GEN-LAST:event_GuestButtonActionPerformed

    private void GuestButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestButton1ActionPerformed
        Bill.request(this);
    }//GEN-LAST:event_GuestButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuestButton;
    private javax.swing.JButton GuestButton1;
    private javax.swing.JButton PhoneButton;
    private javax.swing.JLabel QRLabel;
    // End of variables declaration//GEN-END:variables
}
