
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nemoz
 */
public class Main extends javax.swing.JFrame {

    static Main instance = null;
    
    public Main() {
        instance = this;
        initComponents();
        
        Database.instance.clear();
        loginHintActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recalcTotal = new javax.swing.JButton();
        order = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        list = new javax.swing.JButton();
        loginHint1 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        loginHint2 = new javax.swing.JLabel();
        discountedField = new javax.swing.JTextField();
        finalizeBill = new javax.swing.JButton();
        orderHint = new javax.swing.JLabel();
        loginHint = new javax.swing.JButton();
        loginHint3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        recalcTotal.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        recalcTotal.setText("คิดราคาใหม่");
        recalcTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recalcTotalActionPerformed(evt);
            }
        });

        order.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        order.setText("สั่งอาหาร");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        cancel.setText("ยกเลิก");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        list.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        list.setText("ดูรายการ");
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        loginHint1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        loginHint1.setText("ยอดรวมทั้งหมด");

        totalField.setEditable(false);
        totalField.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        totalField.setText("฿ 0.00");

        loginHint2.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        loginHint2.setText("ลดราคาไปทั้งหมด");

        discountedField.setEditable(false);
        discountedField.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        discountedField.setText("฿ 0.00");

        finalizeBill.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        finalizeBill.setText("สรุปบิล");
        finalizeBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeBillActionPerformed(evt);
            }
        });

        orderHint.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        orderHint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        loginHint.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        loginHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginHintActionPerformed(evt);
            }
        });

        loginHint3.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        loginHint3.setText("ดูบิลอื่นๆ");
        loginHint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginHint3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginHint, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginHint3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(orderHint, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(loginHint1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginHint2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountedField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recalcTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalizeBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginHint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginHint3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderHint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginHint1)
                        .addGap(8, 8, 8)
                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(loginHint2)
                        .addGap(8, 8, 8)
                        .addComponent(discountedField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(recalcTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(finalizeBill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginHintActionPerformed
        setVisible(false);
        new Login(this).addWindowListener(new WindowAdapter() {
            @Override public void windowClosed(WindowEvent e) {
                Member member = Database.instance.order.member;
                String text =  "ผู้ใช้  : " + ((member == null)  ? "ลูกค้าทั่วไป" : "%s (%s)".formatted(member.name, member.phone));
                loginHint.setText(text);
                loginHint.setEnabled(member == null);
                orderHint.setText("" + Database.instance.order.id);
                
                setVisible(true);
            }
        });
    }//GEN-LAST:event_loginHintActionPerformed

    private void finalizeBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeBillActionPerformed
        if (!Database.instance.details.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Thank you for Enjoying the Meals!");
            recalcTotalActionPerformed(null);
            Database.instance.finish();

            dispose();
            new Main();
        }
    }//GEN-LAST:event_finalizeBillActionPerformed

    private void recalcTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recalcTotalActionPerformed
        Database.instance.recalculate();
        Database.instance.bill();
        
        totalField.setText("฿ %.2f".formatted(Database.instance.order.total));
        discountedField.setText("฿ %.2f".formatted(Database.instance.order.discounted));
    }//GEN-LAST:event_recalcTotalActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        setVisible(false);
        new FoodOrder(this).setVisible(true);
    }//GEN-LAST:event_orderActionPerformed

    FoodCancel foodCancelFrame;
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        if (!Database.instance.canBeCancelled.isEmpty())
            foodCancelFrame = new FoodCancel();
    }//GEN-LAST:event_cancelActionPerformed

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        new FoodList();
    }//GEN-LAST:event_listActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        recalcTotalActionPerformed(null);
    }//GEN-LAST:event_formWindowActivated

    private void loginHint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginHint3ActionPerformed
        Bill.request(this);
    }//GEN-LAST:event_loginHint3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField discountedField;
    private javax.swing.JButton finalizeBill;
    private javax.swing.JButton list;
    private javax.swing.JButton loginHint;
    private javax.swing.JLabel loginHint1;
    private javax.swing.JLabel loginHint2;
    private javax.swing.JButton loginHint3;
    private javax.swing.JButton order;
    private javax.swing.JLabel orderHint;
    private javax.swing.JButton recalcTotal;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
