/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Database;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nemoz
 */
public class FrameOrderList extends javax.swing.JFrame {

    DefaultTableModel itemModel;
    
    int orderID;
    
    /**
     * Creates new form FrameOrderList
     */
    public FrameOrderList() {
        initComponents();
    }
    
    void updateTable() {
        try {
            Order order = Database.instance.orders.get(orderID);
            ArrayList<OrderDetail> details = new ArrayList<>();
            
            for (OrderDetail detail : Database.instance.details.values()) {
                if (detail.orderID == order.id) {
                    details.add(detail);
                    
                    boolean isDelivered = true;
                    for (Delivery delivery : Database.instance.deliveries.values()) {
                        if (delivery.orderID == order.id) { isDelivered = delivery.date != null; }
                    }
                    
                    Item item = Database.instance.items.get(Item.getUID(detail.itemID, detail.itemSubID));
                    itemModel.addRow(new Object[] { item.name, item.price, detail.amount, detail.subTotal, isDelivered  });
                }
            }
            
            
        } catch (Exception e) { e.printStackTrace(); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        orderIDField = new javax.swing.JTextField();
        orderPrev = new javax.swing.JButton();
        orderNext = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        orderView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        itemTable.setFont(new java.awt.Font("Cordia New", 0, 24)); // NOI18N
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Price", "Amount", "SubTotal", "Shipped"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemModel = (DefaultTableModel) itemTable.getModel();
        itemTable.getTableHeader().setFont(itemTable.getFont());
        itemTable.setRowHeight(30);
        jScrollPane1.setViewportView(itemTable);

        orderIDField.setFont(new java.awt.Font("Cordia New", 0, 24)); // NOI18N

        orderPrev.setFont(new java.awt.Font("Cordia New", 0, 24)); // NOI18N
        orderPrev.setText("<");
        orderPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderPrevActionPerformed(evt);
            }
        });

        orderNext.setFont(new java.awt.Font("Cordia New", 0, 24)); // NOI18N
        orderNext.setText(">");
        orderNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cordia New", 0, 24)); // NOI18N
        jLabel4.setText("Order ID");

        orderView.setFont(new java.awt.Font("Cordia New", 0, 24)); // NOI18N
        orderView.setText("ดู");
        orderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderView, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderIDField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(orderView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void orderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderViewActionPerformed
        try { orderID = Integer.parseInt(orderIDField.getText()); } catch (Exception e) { e.printStackTrace(); }
        updateTable();
    }//GEN-LAST:event_orderViewActionPerformed

    private void orderPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderPrevActionPerformed
        orderID = Math.max(orderID - 1, 0); updateTable();
    }//GEN-LAST:event_orderPrevActionPerformed

    private void orderNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNextActionPerformed
        orderID = Math.min(orderID + 1, Database.instance.orders.size() - 1); updateTable();
    }//GEN-LAST:event_orderNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOrderList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOrderList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOrderList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOrderList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameOrderList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orderIDField;
    private javax.swing.JButton orderNext;
    private javax.swing.JButton orderPrev;
    private javax.swing.JButton orderView;
    // End of variables declaration//GEN-END:variables
}
