/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nemoz
 */
public class FrameMain extends javax.swing.JFrame {

    private DefaultTableModel tableTableModel;
    private DefaultListModel<String> orderPrepareModel = new DefaultListModel();
    private DefaultListModel<String> orderReadyModel = new DefaultListModel();
    
    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        FrameManager.instance = new FrameManager(this);
        initComponents();
    }
    
    void refresh() {
        reserveButton.setEnabled(Main.instance.availableTable.isEmpty());
        
        tableTableModel.setRowCount(0);
        for (Table table : Main.instance.tables.values()) {
            String occupier = Main.instance.availableTable.contains(table) ? "Available" : "" + Main.instance.orders.get(table).id;
            tableTableModel.addRow(new Object[] { table.id, table.seats, occupier });
        }
        
        orderPrepareModel.removeAllElements();
        for (SubOrder sO : Main.instance.orderPrepareQueue)
            orderPrepareModel.addElement(sO.table.id + " - " + sO.food.name);
        
        orderReadyModel.removeAllElements();
        for (SubOrder sO : Main.instance.orderServingQueue)
            orderReadyModel.addElement(sO.table.id + " - " + sO.food.name);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reserveButton = new javax.swing.JButton();
        queueButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderPreparingList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderReadyList = new javax.swing.JList<>();
        orderListToLeftButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        orderListCancelButton = new javax.swing.JButton();
        orderListToRightButton = new javax.swing.JButton();
        queueLabel = new javax.swing.JLabel();
        queueLabel1 = new javax.swing.JLabel();
        orderButton1 = new javax.swing.JButton();
        orderListServeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        reserveButton.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        reserveButton.setText("Reserve");
        reserveButton.setEnabled(false);
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        queueButton.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        queueButton.setText("Queue");
        queueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queueButtonActionPerformed(evt);
            }
        });

        tableTable.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        tableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table", "Seats", "Occupied"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTableModel = (DefaultTableModel) tableTable.getModel();
        tableTable.getTableHeader().setFont(tableTable.getFont());
        tableTable.setAutoCreateRowSorter(true);
        tableTable.setRowHeight(35);
        tableTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableTable);
        if (tableTable.getColumnModel().getColumnCount() > 0) {
            tableTable.getColumnModel().getColumn(0).setMaxWidth(75);
            tableTable.getColumnModel().getColumn(1).setMaxWidth(75);
        }

        orderPreparingList.setModel(orderPrepareModel);
        orderPreparingList.setFixedCellHeight(25);
        orderPreparingList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        orderPreparingList.setToolTipText("");
        jScrollPane2.setViewportView(orderPreparingList);

        orderReadyList.setModel(orderReadyModel);
        orderReadyList.setFixedCellHeight(25);
        orderReadyList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        orderReadyList.setToolTipText("");
        jScrollPane3.setViewportView(orderReadyList);

        orderListToLeftButton.setFont(new java.awt.Font("Sarabun", 0, 48)); // NOI18N
        orderListToLeftButton.setText("←");
        orderListToLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListToLeftButtonActionPerformed(evt);
            }
        });

        orderButton.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        orderListCancelButton.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        orderListCancelButton.setText("Cancel");
        orderListCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListCancelButtonActionPerformed(evt);
            }
        });

        orderListToRightButton.setFont(new java.awt.Font("Sarabun", 0, 48)); // NOI18N
        orderListToRightButton.setText("→");
        orderListToRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListToRightButtonActionPerformed(evt);
            }
        });

        queueLabel.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        queueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queueLabel.setText("Preparing");

        queueLabel1.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        queueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queueLabel1.setText("Ready for Serving");

        orderButton1.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        orderButton1.setText("Finalize");
        orderButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButton1ActionPerformed(evt);
            }
        });

        orderListServeButton.setFont(new java.awt.Font("Sarabun", 0, 36)); // NOI18N
        orderListServeButton.setText("X");
        orderListServeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListServeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(queueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(queueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderListToLeftButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(orderListToRightButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(orderListServeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(orderListCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(queueLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(queueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(queueLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(queueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orderListToLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderListToRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderListServeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(orderListCancelButton)))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonActionPerformed
        Main.instance.customerEnqueue();
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void queueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueButtonActionPerformed
        FrameManager.instance.next(new FrameQueue());
    }//GEN-LAST:event_queueButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        refresh();
    }//GEN-LAST:event_formWindowActivated

    private void orderListToLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListToLeftButtonActionPerformed
        int selectedIndex = orderReadyList.getSelectedIndex();
        if (selectedIndex >= 0) {
            SubOrder sO = Main.instance.orderServingQueue.remove(selectedIndex);
            Main.instance.orderPrepareQueue.push(sO);
            refresh();
        }
    }//GEN-LAST:event_orderListToLeftButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        int selectedRow = tableTable.getSelectedRow();
        if (selectedRow >= 0) {
            FrameManager.instance.next(new FrameOrder((String) tableTable.getValueAt(selectedRow, 0)));
        }
    }//GEN-LAST:event_orderButtonActionPerformed

    private void orderListCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListCancelButtonActionPerformed
        int selectedIndex;
        
        selectedIndex = orderPreparingList.getSelectedIndex();
        if (selectedIndex >= 0) {
            Main.instance.cancelSubOrder(Main.instance.orderPrepareQueue.get(selectedIndex));
            refresh();
        }
        
        selectedIndex = orderReadyList.getSelectedIndex();
        if (selectedIndex >= 0) {
            Main.instance.cancelSubOrder(Main.instance.orderServingQueue.get(selectedIndex));
            refresh();
        }
    }//GEN-LAST:event_orderListCancelButtonActionPerformed

    private void orderListToRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListToRightButtonActionPerformed
        int selectedIndex = orderPreparingList.getSelectedIndex();
        if (selectedIndex >= 0) {
            SubOrder sO = Main.instance.orderPrepareQueue.remove(selectedIndex);
            Main.instance.orderServingQueue.push(sO);
            refresh();
        }
    }//GEN-LAST:event_orderListToRightButtonActionPerformed

    private void orderButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButton1ActionPerformed
        int selectedRow = tableTable.getSelectedRow();
        if (selectedRow >= 0) {
            String tbName = (String) tableTable.getValueAt(selectedRow, 0);
            Table table = Main.instance.tables.get(tbName);
            
            if (!Main.instance.availableTable.contains(table))
                FrameManager.instance.next(new FrameFinalize(tbName));
        }
    }//GEN-LAST:event_orderButton1ActionPerformed

    private void orderListServeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListServeButtonActionPerformed
        int selectedIndex = orderReadyList.getSelectedIndex();
        if (selectedIndex >= 0) {
            SubOrder sO = Main.instance.orderServingQueue.remove(selectedIndex);
            Main.instance.serveSubOrder(sO);
            refresh();
        }
    }//GEN-LAST:event_orderListServeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton orderButton1;
    private javax.swing.JButton orderListCancelButton;
    private javax.swing.JButton orderListServeButton;
    private javax.swing.JButton orderListToLeftButton;
    private javax.swing.JButton orderListToRightButton;
    private javax.swing.JList<String> orderPreparingList;
    private javax.swing.JList<String> orderReadyList;
    private javax.swing.JButton queueButton;
    private javax.swing.JLabel queueLabel;
    private javax.swing.JLabel queueLabel1;
    private javax.swing.JButton reserveButton;
    private javax.swing.JTable tableTable;
    // End of variables declaration//GEN-END:variables
}
